project:
  type: website
  output-dir: _site

website:
  title: "Faadil Mustun"
  favicon: dolphin_icon.png
  navbar:
    background: primary
    right:
      - text: About
        href: index.qmd#about
      - text: News
        href: index.qmd#news
      - text: Publications
        href: index.qmd#publications
      - text: Talks
        href: index.qmd#selected-talks-posters
      - text: Education
        href: index.qmd#education

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: head.html
    toc: false
    grid:
      body-width: 1050px
      margin-width: 80px
    metadata:
      description: >
        Faadil Mustun is a postdoctoral researcher in computational
        biology at ENS Paris studying dolphin communication using
        machine learning and bioacoustics.

resources:
  - google870b7177ea57b41b.html